VivaMVC5/Controllers/ExportController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VivaMVC5.Helper;
using VivaMVC5.Models;

namespace VivaMVC5.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ExportController : Controller
    {
        private ProductDBContext _context = new ProductDBContext();
        // GET: Export
        public ActionResult Index()
        {
            ViewBag.Products = _context.Products;
            ViewBag.Customers = _context.Customers;
            return View();
        }


        [HttpPost]
        public ActionResult WorkCustomer()
        {
            var workCustomer = new WorkCustomers();
            workCustomer.CustomerId = int.Parse(Request.Form["customerId"]);
            workCustomer.Money = int.Parse(Request.Form["totalMoney"]);
            workCustomer.CreatedDate = DateTime.UtcNow;

            _context.WorkCustomers.Add(workCustomer);
            _context.SaveChanges();

            List<int> water = new List<int>();
            List<int> bottle = new List<int>();
            water.AddRange(new int[] { int.Parse(Request.Form["waterVictory"]), int.Parse(Request.Form["waterViva"]), int.Parse(Request.Form["waterBirico"]) });
            bottle.AddRange(new int[] { int.Parse(Request.Form["bottleVictory"]), int.Parse(Request.Form["bottleViva"]), int.Parse(Request.Form["bottleBirico"]) });


            for (int i = 1; i <= 3; i++)
            {
                var workCustomerDetail = new WorkCustomerDetails();
                workCustomerDetail.ProductId = i;
                workCustomerDetail.Water = water[i - 1];
                workCustomerDetail.Bottle = bottle[i - 1];
                workCustomerDetail.WorkCustomersId = workCustomer.Id;

                _context.WorkCustomerDetails.Add(workCustomerDetail);

                //TODO: Refactoring in next version
                var product = new Products();
                product.Bottle += workCustomerDetail.Bottle;
                product.WaterBottle += workCustomerDetail.Water;

                _context.Entry(product).State = EntityState.Modified;
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult GetWorkCustomers([DataSourceRequest]DataSourceRequest request)
        {
            var workCustomers = _context.WorkCustomers.Include(c => c.Customer);
            return Json(workCustomers.ToDataSourceResult(request));
        }

        public ActionResult GetWorkCustomerDetails(int workCustomerId, [DataSourceRequest] DataSourceRequest request)
        {
            var workCustomerDetails = _context.WorkCustomerDetails.Where(cd => cd.WorkCustomersId == workCustomerId).ToDataSourceResult(request);
            return Json(workCustomerDetails);
        }
    }
}

VivaMVC5/Controllers/FinanceController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VivaMVC5.Helper;
using VivaMVC5.Models;

namespace VivaMVC5.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class FinanceController : Controller
    {
        private ProductDBContext _context = new ProductDBContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Read([DataSourceRequest]DataSourceRequest request)
        {
            var check = _context.Finances.ToDataSourceResult(request);
            return Json(check);
        }

        [AcceptVerbs("Post")]
        public ActionResult Create([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]IEnumerable<Finances> finances)
        {
            if (finances != null && ModelState.IsValid)
            {
                foreach (var finance in finances)
                {
                    _context.Finances.Attach(finance);
                    _context.Finances.Add(finance);
                    _context.SaveChanges();
                }
            }

            return Json(finances.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs("Post")]
        public ActionResult Update([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]IEnumerable<Finances> finances)
        {
            if (finances != null && ModelState.IsValid)
            {
                foreach (var finance in finances)
                {
                    _context.Entry(finance).State = EntityState.Modified;
                    _context.SaveChanges();
                }
            }

            return Json(finances.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs("Post")]
        public ActionResult Destroy([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")]IEnumerable<Finances> finances)
        {
            if (finances.Any())
            {
                foreach (var finance in finances)
                {
                    _context.Finances.Attach(finance);
                    _context.Finances.Remove(finance);
                    _context.SaveChanges();
                }
            }

            return Json(finances.ToDataSourceResult(request, ModelState));
        }
    }
}

VivaMVC5/Controllers/ImportController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VivaMVC5.Helper;
using VivaMVC5.Models;

namespace NuocTinhKhietViva.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ImportController : Controller
    {
        private ProductDBContext _context = new ProductDBContext();

        public ActionResult Index()
        {
            ViewBag.Products = _context.Products;
            return View();
        }

        [HttpPost]
        public ActionResult WorkSupplier()
        {
            var model = new WorkSuppliers();
            model.ProductId = int.Parse(Request.Form["productId"]);
            model.Water = int.Parse(Request.Form["countWater"]);
            model.Bottle = int.Parse(Request.Form["countBottle"]);
            model.CreatedDate = DateTime.UtcNow;

            _context.WorkSuppliers.Add(model);

            //TODO: Refactoring in next version
            var product = new Products();
            product.Bottle += model.Bottle;
            product.WaterBottle += model.Water;

            _context.Entry(product).State = EntityState.Modified;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult GetWorkSuppliers([DataSourceRequest]DataSourceRequest request)
        {
            var workSuppliers = _context.WorkSuppliers.Include(s => s.Product);
            return Json(workSuppliers.ToDataSourceResult(request));
        }
    }
}

VivaMVC5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - NuocTinhKhietViva</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/kendo/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/kendo")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NuocTinhKhietViva", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                    @if (User.IsInRole("Administrator"))
                    {
                        <li>@Html.ActionLink("Nhập kho", "Index", "Import")</li>
                        <li>@Html.ActionLink("Xuất kho", "Index", "Export")</li>
                        <li>@Html.ActionLink("Thu chi", "Index", "Finance")</li>
                    }
                    <li>@Html.ActionLink("Giới thiệu", "About", "Home")</li>
                    <li>@Html.ActionLink("Liên Hệ", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - NuocTinhKhietViva</p>
        </footer>
    </div>

   
    @RenderSection("scripts", required: false)
</body>
</html>